/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List indexed agents (keyset-paginated) */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by chain name (e.g. 'base') or chain_id (e.g. '8453') */
                    chain?: string;
                    limit?: number;
                    /** @description Opaque keyset cursor from a prior response's next_cursor */
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentList"];
                    };
                };
                /** @description invalid cursor or query */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{chain}/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single agent by chain and id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    chain: string;
                    /** @description uint256 as decimal string */
                    agent_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentDetail"];
                    };
                };
                /** @description agent or chain not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health, chain registry, indexed agent count */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Agent: {
            /**
             * @description uint256 as decimal string
             * @example 42
             */
            agent_id: string;
            agent_uri?: string | null;
            /** @description 0x-prefixed; cleared on ownership Transfer (spec gotcha) */
            agent_wallet?: string | null;
            /** @example base */
            chain: string;
            /**
             * Format: int64
             * @example 8453
             */
            chain_id: number;
            /** @description 0x-prefixed 20-byte hex */
            owner: string;
            /** Format: date-time */
            registered_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AgentDetail: {
            data: components["schemas"]["Agent"];
            source: string;
            /** Format: int64 */
            staleness_ms: number;
        };
        AgentList: {
            data: components["schemas"]["Agent"][];
            /** @description Opaque; pass verbatim as ?cursor= to page */
            next_cursor?: string | null;
            /** @enum {string} */
            source: "db" | "cache" | "rpc";
            /** Format: int64 */
            staleness_ms: number;
        };
        ChainHealth: {
            /** Format: int64 */
            agents_indexed: number;
            /** Format: int64 */
            chain_id: number;
            is_testnet: boolean;
            name: string;
        };
        Error: {
            error: {
                /** @example AGENT_NOT_FOUND */
                code: string;
                /** @example api.lookup */
                evaluator: string;
                override_hint?: string | null;
                /** @example v1 */
                policy_version: string;
            };
        };
        Health: {
            /** Format: int64 */
            agents_indexed: number;
            chains: components["schemas"]["ChainHealth"][];
            /** @enum {string} */
            status: "ok";
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
